---
 - hosts: localhost
   connection: local
   become: true
 
  tasks:
    - include: tasks/users.yml
    - include: tasks/cron.yml
    - include: tasks/packages.yml
    - include: tasks/get_service_status.yml
    - include: tasks/sys_conf.yml

