- name: Install packages
  apt:
    name: 
      - htop
      - mc
      - tmux
      - vim
      - openssh-server
      - xymon-client
      - nfs-common
      - neofetch
      - ntpdate
      - terminator
      - snmpd
  when: (ansible_facts['os_family'] == "Debian" )

- name: Install packages
  yum:
    name:
      - htop
      - mc
      - tmux
      - vim
      - openssh-server
      - snmpd
  when: (ansible_facts['os_family'] == "RedHat" )


