- name: copy multipath.conf to /etc
  copy:
    src: files/multipath.conf
    dest: /etc/multipath.conf
    owner: root
    group: root
    mode: 0440
  when: multipathtools_status.stdout=='active'
  notify: restart multipathtools

- name: copy issue /etc
  copy:
    src: files/issue
    dest: /etc/issue
    owner: root
    group: root
    mode: 0644

- name: copy snmpd.conf to /etc/snmp/
  copy:
    src: files/snmpd.conf
    dest: /etc/snmp/snmpd.conf
    owner: root
    group: root
    mode: 0644
    #  notify: restart snmpd

- name: Disable root login with password via ssh
  lineinfile:
    path: /etc/ssh/sshd_config
    state: absent
    regexp: "^PermitRootLogin"
    line: "PermitRootLogin yes"
  notify: restart sshd

- name: Disable root login with password via ssh
  lineinfile:
    path: /etc/ssh/sshd_config
    state: present
    regexp: "^PermitRootLogin"
    line: "PermitRootLogin prohibit-password"
  notify: restart sshd

#- name: Restart multipath-tools service, if config changed
#  ansible.builtin.service:
#    name: multipath-tools
#    state: restarted
#  when: multipathtools_conf.changed

- name: ensure rsyslog points to iron loghost Redhat/Centos
  lineinfile:
    path: /etc/rsyslog.conf
    state: present
    regexp: "^'*.*'"
    line: "*.* @@loghost.ofh.lan:514"
  notify: restart rsyslogd
  when: (ansible_facts['os_family'] == "RedHat" )
  notify:
    - restart rsyslogd    

- name: ensure rsyslog points to iron loghost ubuntu/debian
  lineinfile:
    path: /etc/rsyslog.d/50-default.conf
    state: present
    regexp: "^'*.*'"
    line: "*.* @@loghost.ofh.lan:514"
  notify: restart rsyslogd
  when: (ansible_facts['os_family'] == "Debian" )
  notify: restart rsyslogd    

- name: ensure /etc/bash.bashrc contains neofetch
  lineinfile:
    path: /etc/bash.bashrc
    state: present
    regexp: "^neofetch"
    line: "neofetch"
  when: (ansible_facts['os_family'] == "Debian" )

- name: ensure xymon-client points to mercury 192.168.2.26
  lineinfile:
    path: /etc/default/xymon-client
    state: present
    regexp: "^XYMONSERVERS"
    line: 'XYMONSERVERS="192.168.2.26"'
  notify: restart xymon-client

  #- name: ensure hosts file contains
  #lineinfile:
  #  path: /etc/hosts
  #  state: present
  #  regexp: "^192.168.2.35"
  #  line: "192.168.2.35  iodine iodine.ofh.lan"


- name: Change /etc/sudoers.d perms
  ansible.builtin.file:
    path: /etc/sudoers.d
    owner: root
    group: root
    mode: '0750'

- name: Create /home/dave/.ssh if it does not exist
  ansible.builtin.file:
    path: /home/dave/.ssh
    state: directory
    owner: dave
    group: dave
    mode: '0740'

    #- name: Recursively change ownership of /home/dave/.ssh
    #ansible.builtin.file:
    #path: /home/dave/.ssh
    #state: directory
    #recurse: yes
    #user: dave
    #group: dave

- name: copy over authorized_keys file for dave-yubi
  copy:
    src: files/authorized_keys
    dest: /home/dave/.ssh/authorized_keys
    owner: dave
    group: dave
    mode: 0644

- name: Stop service snmpd 
  ansible.builtin.systemd:
    name: snmpd
    state: stopped

- name: Disable snmpd service
  ansible.builtin.systemd:
    name: snmpd
    enabled: no
    masked: no
